### ISSUE TITLE
There's no main.py

### ISSUE THREAD

**Issue by doitcode1999** [rootvisionai/few_shot_sam#20]
if i use the command "python main.py"
Then, I got the error. (There's no main.py)
How can i fix the error?

**Comment by rootvisionai** [comment]
We have changed the structure, I will update the documentation

**Comment by doitcode1999** [comment]
Thank you for posting your reply!

**Comment by abhigarg** [comment]
check branches other than the main branch. There is a main.py but not sure if the code is stable or not.

**Comment by doitcode1999** [comment]
> check branches other than the main branch. There is a main.py but not sure if the code is stable or not.

Excuse me, where can I find information about main ?

**Comment by rootvisionai** [comment]
Hi all, we have changed the structure and the way it works. With one single main.py, it wasn't so easy to maintain. I will update the readme this weekend with all new instructions about how it works, what to do etc.

**Comment by doitcode1999** [comment]
> Hi all, we have changed the structure and the way it works. With one single main.py, it wasn't so easy to maintain. I will update the readme this weekend with all new instructions about how it works, what to do etc.


Thank you very much for your reply.
Have a good day!

**Comment by rootvisionai** [comment]
updated readme, made some code changes as well. please try and check it out, if there is any other issue, do not hesitate to write or fix and suggest change :)

**Comment by doitcode1999** [comment]
Thank you very much for your reply! :)
