### ISSUE TITLE
What is the method used in  few shot ? 

### ISSUE THREAD

**Issue by senlin-ali** [rootvisionai/few_shot_sam#22]
hi , great work , i want to know What is the method used in  few shot ?  where can i find this method

**Comment by doitcode1999** [comment]
Have you checked your config.yaml file?

**Comment by rootvisionai** [comment]
You're not able to find it somewhere. We extract features by using sam, then we index the features with point coordinates that the user has given. After that We use the positive and negative features that we indexed to train a linear layer with the exact solution in one step, then we make inference on query images by using this linear layer.
